import 'dotenv/config';
import mongoose from 'mongoose';
import connectDB from './config/db.js';
import User from './models/User.js';
import Category from './models/Category.js';
import Product from './models/Product.js';
import Order from './models/Order.js';

// Generated by the API itself (see utils/placeholder.js), so it works offline
const img = (name, v = 0) => `/api/placeholder/${encodeURIComponent(name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''))}.svg${v ? `?v=${v}` : ''}`;

const CATEGORIES = [
  ['Electronics', 'Gadgets, audio and accessories'],
  ['Fashion', 'Clothing, bags and footwear'],
  ['Home & Living', 'Decor, kitchen and everyday essentials'],
  ['Beauty', 'Skincare and personal care'],
  ['Sports', 'Gear and activewear'],
];

// [name, category, price, compareAt, stock, featured, brand, description]
const PRODUCTS = [
  ['Wireless Noise-Cancelling Headphones', 'Electronics', 4999, 6499, 40, true, 'SoundCore', 'Over-ear Bluetooth headphones with 30-hour battery life and active noise cancellation.'],
  ['Mechanical Keyboard 75%', 'Electronics', 3299, 0, 25, true, 'KeyForge', 'Hot-swappable mechanical keyboard with RGB backlight and USB-C.'],
  ['Portable Power Bank 20,000mAh', 'Electronics', 1299, 1599, 80, false, 'VoltGo', 'Fast-charging power bank with dual USB-A and one USB-C port.'],
  ['Smart Fitness Watch', 'Electronics', 2899, 3499, 30, true, 'FitPulse', 'Heart-rate, sleep tracking and 7-day battery life.'],
  ['Classic Cotton T-Shirt', 'Fashion', 399, 0, 200, false, 'Basic Co.', 'Soft 100% cotton crew-neck tee in a relaxed fit.'],
  ['Slim Fit Denim Jeans', 'Fashion', 1299, 1699, 60, true, 'Indigo', 'Stretch denim with a modern slim cut.'],
  ['Canvas Backpack', 'Fashion', 1099, 0, 45, false, 'Trailmate', 'Water-resistant canvas backpack with a padded 15" laptop sleeve.'],
  ['Leather Slip-On Sneakers', 'Fashion', 1899, 2299, 35, false, 'Stride', 'Comfortable everyday sneakers with cushioned insoles.'],
  ['Ceramic Dinner Set (16 pcs)', 'Home & Living', 2199, 0, 20, false, 'Homely', 'Dishwasher-safe dinner set for four.'],
  ['Scented Soy Candle', 'Home & Living', 349, 0, 120, true, 'Glow', 'Hand-poured soy candle, 40-hour burn time.'],
  ['Memory Foam Pillow', 'Home & Living', 899, 1199, 50, false, 'DreamWell', 'Ergonomic pillow that keeps its shape night after night.'],
  ['Vitamin C Brightening Serum', 'Beauty', 799, 0, 90, true, 'Lumière', '30ml serum with 15% vitamin C for a brighter complexion.'],
  ['Hydrating Face Moisturizer', 'Beauty', 649, 0, 75, false, 'Lumière', 'Lightweight daily moisturizer with hyaluronic acid.'],
  ['Non-Slip Yoga Mat', 'Sports', 899, 1099, 55, false, 'FlexFit', '6mm thick eco-friendly yoga mat with carry strap.'],
  ['Adjustable Dumbbell Set', 'Sports', 3499, 0, 4, true, 'IronPeak', 'Space-saving adjustable dumbbells, 2–20kg.'],
  ['Insulated Water Bottle 750ml', 'Sports', 549, 0, 3, false, 'HydroKeep', 'Keeps drinks cold 24 hours or hot 12 hours.'],
];

// Older versions of this project created these accounts with published passwords.
// If one of them is still in the database with its ORIGINAL password, it is removed
// (an account whose password was changed is left alone).
const LEGACY_DEMO = [
  ['admin@shop.com', 'Admin123!'],
  ...['maria', 'juan', 'angela', 'carlo', 'bea', 'miguel', 'trisha', 'paolo'].map((n) => [`${n}@example.com`, 'Customer123!']),
];

async function removeLegacyDemoAccounts() {
  const found = await User.find({ email: { $in: LEGACY_DEMO.map(([e]) => e) } }).select('+password');
  const ids = [];
  for (const u of found) {
    const demoPassword = LEGACY_DEMO.find(([e]) => e === u.email)[1];
    // eslint-disable-next-line no-await-in-loop
    if (await u.matchPassword(demoPassword)) ids.push(u._id);
  }
  if (!ids.length) return;
  await Promise.all([User.deleteMany({ _id: { $in: ids } }), Order.deleteMany({ user: { $in: ids } })]);
  console.log(`Removed ${ids.length} old demo account${ids.length === 1 ? '' : 's'} that still used the published sample password (and their sample orders).`);
}

// Accounts are never touched here: the store's catalogue (categories, products) and orders are wiped, user accounts stay.
async function destroy() {
  await Promise.all([Category.deleteMany(), Product.deleteMany(), Order.deleteMany()]);
}

async function run() {
  await connectDB();
  await removeLegacyDemoAccounts();

  const force = process.argv.includes('--force');
  if (!force && (await Product.estimatedDocumentCount()) + (await Category.estimatedDocumentCount()) > 0) {
    // --if-empty is used by "npm start": stay quiet when the shop already has data
    if (!process.argv.includes('--if-empty')) {
      console.log('\nThe shop already has products, so nothing was changed.');
      console.log('To wipe the products, categories and orders and load the sample catalogue again, run:  npm run reset\n');
    }
    return;
  }
  await destroy();
  if (process.argv.includes('--destroy')) {
    console.log('Products, categories and orders cleared (user accounts were kept).');
    return;
  }

  const cats = {};
  for (const [name, description] of CATEGORIES) cats[name] = await Category.create({ name, description });

  let count = 0;
  for (const [name, cat, price, compareAtPrice, stock, isFeatured, brand, description] of PRODUCTS) {
    // create() one at a time so the slug hook can check uniqueness
    // eslint-disable-next-line no-await-in-loop
    await Product.create({
      name, price, compareAtPrice, stock, isFeatured, brand, description,
      category: cats[cat]._id,
      images: [img(name), img(name, 1)],
    });
    count += 1;
  }

  console.log('\nSeed complete.');
  console.log(`  ${CATEGORIES.length} categories and ${count} sample products loaded. No user accounts were created.`);
  console.log('  Register on the website to create an account (always a customer).\n');
}

run()
  .catch((e) => { console.error(e); process.exitCode = 1; })
  .finally(() => mongoose.disconnect());
